[[main]]
none = "none"

[[main]]
name = "Join Us"
pre = "star"
pageRef = "pages/join_us"
identifier = "Oux6KC42kf"
weight = 9_999

[[main]]
name = "News"
pre = "fire"
pageRef = "news"
identifier = "j4KkWsVtcj"
weight = 9_999

[[main]]
name = "Members"
pre = "heart"
pageRef = "pages/members"
identifier = "97OmlmaE8P"
weight = 9_999

[[footer]]
none = "none"

[[footer]]
name = "Email Us"
pre = "email"
url = "mailto:osct@unito.it"
identifier = "K9FEoh4Igs"
weight = 1

[[footer]]
name = "Instagram"
pre = "instagram"
url = "https://www.instagram.com/osctorino/"
identifier = "0Gr5BdORyo"
weight = 9_999

[[footer]]
name = "Linkedin"
pre = "linkedin"
url = "https://www.linkedin.com/company/open-science-community-torino/"
identifier = "f2b461fa83"
weight = 2
